version: '3.8'
services:
  app:
    build: .
    ports:
      - '3001:3000'
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USERNAME: nest_user
      DATABASE_PASSWORD: nest_pass
      DATABASE_NAME: green_days

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: nest_user
      POSTGRES_PASSWORD: nest_pass
      POSTGRES_DB: green_days
    ports:
      - '5434:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
